baseURL = "https://blog.herecura.eu/"
languageCode = "en-us"
title = "BlackIkeEagle's blog"
theme = ["hugo-notice", "hugo-video", "hyde"]
[params]
  description = "Thoughts to remember, and other random stuff."
  copyright = "2014"
  layoutReverse = true
  disqusShortname = "blackikeeaglesblog"
[[menu.main]]
    name = "Blogs"
    weight = -200
    identifier = "blogs"
    url = "/blog/"
[[menu.main]]
    name = "Talks"
    weight = -150
    url = "/talk/"
[[menu.main]]
    name = "About me"
    weight = -100
    url = "https://herecura.eu"
[[menu.blogroll]]
    name = "Docker West"
    weight = -120
    identifier = "dockerwest"
    url = "https://dockerwest.github.io"
[[menu.blogroll]]
    name = "Jachim Coudenys"
    weight = -110
    identifier = "coudenysj"
    url = "https://blog.jachim.be"
[[menu.blogroll]]
    name = "Tom Van Herrewege"
    weight = -110
    identifier = "Miljar"
    url = "https://miljar.github.io"
[[menu.blogroll]]
    name = "Mattias Geniar"
    weight = -100
    identifier = "Mattias Geniar"
    url = "https://ma.ttias.be/blog/"
